name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build site
        run: pnpm build

      - name: Add .nojekyll
        run: touch dist/analog/public/.nojekyll

      - name: Deploy to GitHub Pages
        run: |
          npx gh-pages -d dist/analog/public -b gh-pages \
            -b gh-pages \
            -u "GitHub Actions <actions@github.com>" \
            -r "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
