name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build

      - name: Add .nojekyll and 404.html
        run: |
          touch dist/analog/public/.nojekyll
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"/><title>Redirecting…</title><meta http-equiv="refresh" content="0; url=/tx-nas/" /></head><body><p>Redirecting…</p></body></html>' > dist/analog/public/404.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/analog/public
